### ISSUE TITLE
undefined symbol: iJIT_NotifyEvent when running test

### ISSUE THREAD

**Issue by ghost** [atzkenneth/dragonfly_gen#3]
Hi,

I followed the installation instructions, and then get the following error when running the test script:

`python test_pyg.py
Traceback (most recent call last):
  File "test_pyg.py", line 5, in <module>
    import torch
  File "/home/evehom/miniconda3/envs/dragonfly_gen/lib/python3.8/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/evehom/miniconda3/envs/dragonfly_gen/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent`

It seems that Dragonfly does not need GPU support, is this correct?

Please advise on how to proceed.

Thanks/Evert

**Comment by viv3kanand** [comment]
Add mkl=2024.0 to the environment.yml file. It solves the issue

Check [https://github.com/pytorch/pytorch/issues/123097]() for details

**Comment by ghost** [comment]
```
python test_pyg.py
torch_geometric.__version__: 2.3.0
torch.__version__: 1.13.1
rdkit.__version__: 2022.09.5
```

Thank you!

BW/Evert
